// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using iTaskAPI.Connection;

#nullable disable

namespace iTaskAPI.Migrations
{
    [DbContext(typeof(ConnectionDB))]
    [Migration("20251111113455_AddUsernameToUtilizador")]
    partial class AddUsernameToUtilizador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("iTaskAPI.Models.Gestor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdUtilizador")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IdUtilizador")
                        .IsUnique();

                    b.ToTable("Gestores");
                });

            modelBuilder.Entity("iTaskAPI.Models.Programador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdGestor")
                        .HasColumnType("integer");

                    b.Property<int>("IdUtilizador")
                        .HasColumnType("integer");

                    b.Property<string>("NivelExperiencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdGestor");

                    b.HasIndex("IdUtilizador")
                        .IsUnique();

                    b.ToTable("Programadores");
                });

            modelBuilder.Entity("iTaskAPI.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPrevistaFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataPrevistaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataRealFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataRealInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("EstadoAtual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdGestor")
                        .HasColumnType("integer");

                    b.Property<int>("IdProgramador")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoTarefa")
                        .HasColumnType("integer");

                    b.Property<string>("OrdemExecucao")
                        .HasColumnType("text");

                    b.Property<int?>("StoryPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdGestor");

                    b.HasIndex("IdProgramador");

                    b.HasIndex("IdTipoTarefa");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("iTaskAPI.Models.TipoTarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TiposTarefa");
                });

            modelBuilder.Entity("iTaskAPI.Models.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("iTaskAPI.Models.Gestor", b =>
                {
                    b.HasOne("iTaskAPI.Models.Utilizador", "Utilizador")
                        .WithOne("Gestor")
                        .HasForeignKey("iTaskAPI.Models.Gestor", "IdUtilizador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("iTaskAPI.Models.Programador", b =>
                {
                    b.HasOne("iTaskAPI.Models.Gestor", "Gestor")
                        .WithMany("Programadores")
                        .HasForeignKey("IdGestor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("iTaskAPI.Models.Utilizador", "Utilizador")
                        .WithOne("Programador")
                        .HasForeignKey("iTaskAPI.Models.Programador", "IdUtilizador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gestor");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("iTaskAPI.Models.Tarefa", b =>
                {
                    b.HasOne("iTaskAPI.Models.Gestor", "Gestor")
                        .WithMany("Tarefas")
                        .HasForeignKey("IdGestor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("iTaskAPI.Models.Programador", "Programador")
                        .WithMany("Tarefas")
                        .HasForeignKey("IdProgramador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("iTaskAPI.Models.TipoTarefa", "TipoTarefa")
                        .WithMany("Tarefas")
                        .HasForeignKey("IdTipoTarefa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gestor");

                    b.Navigation("Programador");

                    b.Navigation("TipoTarefa");
                });

            modelBuilder.Entity("iTaskAPI.Models.Gestor", b =>
                {
                    b.Navigation("Programadores");

                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("iTaskAPI.Models.Programador", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("iTaskAPI.Models.TipoTarefa", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("iTaskAPI.Models.Utilizador", b =>
                {
                    b.Navigation("Gestor");

                    b.Navigation("Programador");
                });
#pragma warning restore 612, 618
        }
    }
}
